all: # группа по умолчанию
  children: # указываем, что это вложенные хосты
   geek: # задаём имя группы, может быть любым
     hosts: #
       192.168.11.51: # указываем ip или FQDN
         ansible_user: root
         server_name: localhost
